# -*- coding: utf-8 -*-
"""day_2aiml.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EaXpslZEu31jFSRaELH2xeO-G1Qu5z61

''' Day 2: Python Fundamentals

 Name: Bhuvanesh Himmat Deore

   Contact no : 8080649149

   Email :bhuvideore18@gmail.com

   Description : Topics that are covered on day 2

   Topics : 1) Arithmatic operator ,2) concatination ,3) strting replication ,4) type conversion, 5) the round function, 6) the absalute function ,
   7) comparison operator
"""

a = "alice"
b= "Bob"
c = " "

#Arithmatic operator

a=15
b= 10

print (a+b)  # Addition
print (a-b)  # Sub
print (a*b)  # multi
print (a**b) # exponent
print (a/b)  # division
print (a//b) #Integer division
print (a%b)  #Modulus

#concatination
d=a+c+b
print("the conatenated stringis : ",d)

#strting replication
name = "Bhuvi"
print(name * 3)

#let's change the value of variable
var1=3.14
print(var1)
var1="Alice"
print(var1)

# variable naming rules

#type conversion
x = "10"

print("my age is "+str(x))

#the round function

y = 7.099
round(y)

# the absalute function
n=-10
print(abs(n))

5==5

5!=6

5<6

5>4

marks = int(input("Enter the marks: "))

if marks>50:
  print("B")
elif marks>=70:
  print("a")
else:
  print("F")

print("SYSTEM: You are locked inside the Python Vault.")
print("Your Mission: Collect enough power to escape the vault.")

#level 1
energy=10
print("LEVEL 1 — ENERGY CORE")
print(f"You start with {energy} energy.")

found = int(input("You found an energy crystal worth: "))

energy = energy + found

print("Energy collected!")
print(f"Your energy is now: {energy}")

#level 2
print("LEVEL 2 — POWER BOOST")

boost = int(input("Choose your power multiplier (1–5): "))

powered_energy = energy * boost

print("POWER ACTIVATED!")
print(f"Your energy became: {powered_energy}")


#level 3
print("LEVEL 3 — LASER WALL")

laser_cost = int(input("How much energy does the laser wall cost? "))

remaining = powered_energy - laser_cost

print("Laser wall disabled!")
print(f"Energy remaining: {remaining}")

#level 4
print("LEVEL 4 — TEAM UP")

team_size = int(input("How many hackers are in your team? "))

share = remaining / team_size

print(f"Each hacker gets {share:.2f} energy.")

#level 5
print("LEVEL 5 — BUILD THE SQUAD")

energy_per_hacker = int(input("Energy required per hacker: "))

full_hackers = remaining // energy_per_hacker

print(f"You can fully power {full_hackers} hackers.")


#level 6
leftover = remaining % energy_per_hacker

print(f"Energy left unused: {leftover}")

#level 7
print("LEVEL 7 — THE FINAL VAULT")

power_level = int(input("Enter your final power level: "))

final_power = power_level ** 2

print(f"Your final power is: {final_power}")

#escape

print("VAULT UNLOCKED!")


print(f"""
 MISSION COMPLETE!

 Final energy      : {remaining}
 Full hackers      : {full_hackers}
 Leftover energy   : {leftover}
 Final power       : {final_power}

You didn't just learn operators.
You used them to build something.

WELCOME TO PYTHON.
""")

